### ISSUE TITLE
gcc poison

### ISSUE THREAD

**Issue by eugpermar** [edenhill/mklove#14]
This header warns about the use of "unsafe" functions like strcat, strcpy, etc... in order to replace them for bound safe versions (strncat, strncpy,...)

https://github.com/leafsr/gcc-poison

Do you think that they should be included in mklove, in a similar way to good_cflags?

**Comment by edenhill** [comment]
They are not unsafe, but their use might be, but what is safe in C any way?
I think any such warnings are a bogus generalization.

Perfectly fine wine:
````
    char dst[64], src[32];
    snprintf(src, sizeof(src), "my num %d", anum);
    strcpy(dst, src);
````

A good compiler or static code analyser will find misuses.

**Comment by eugpermar** [comment]
Well, I think I use a bad example. Hurries are never goods. In fact, even a strcpy(dst,"FIXED_STR") is ok.

I was more focused in functions like strtok (easily changeable by strtok_r), sprintf -> snprintf, etc. They are not bad by default, but I think that it doesn't worth to use the "unsafe" version.

Anyway, now I think that the list is short enough to select the poisoned function by hand. I will close the issue, thanks!
