### ISSUE TITLE
Support for `--disable-option-checking`

### ISSUE THREAD

**Issue by vincentbernat** [edenhill/mklove#28]
Autoconf supports the [`--disable-option-checking`](https://www.gnu.org/software/autoconf/manual/autoconf-2.68/html_node/Option-Checking.html) option. Debian started using it and since mklove mimics itself as autoconf, it makes the build of related tools fail.

Also, more globally, autoconf usually only warns about unknown options. I don't know if mklove doesn't do this by choice.

**Comment by edenhill** [comment]
> Also, more globally, autoconf usually only warns about unknown options. I don't know if mklove doesn't do this by choice.

I don't particularly like that behaviour in software, it is better to fail fast.

Will make sure to add --disable-option-checking to librdkafka and kafkacat.

**Comment by edenhill** [comment]
Done

**Comment by rkahv** [comment]
@edenhill Hi, I am currently running into the same issue with libserdes. Could you please add this option also to libserdes? Thanks!
