### ISSUE TITLE
Colored output doesn't work

### ISSUE THREAD

**Issue by Whissi** [edenhill/mklove#5]
Hi,

colored output doesn't work for me:
```
make[1]: Leaving directory '/usr/local/src/librdkafka-0.8.6/work/librdkafka-0.8.6/examples'
\033[33mUpdating CONFIGURATION.md\033[0m
\033[033mChecking  integrity\033[0m
CONFIGURATION.md               \033[032mOK\033[0m
examples/rdkafka_example       \033[032mOK\033[0m
examples/rdkafka_performance   \033[032mOK\033[0m
examples/rdkafka_example_cpp   \033[032mOK\033[0m
make[1]: Entering directory '/usr/local/src/librdkafka-0.8.6/work/librdkafka-0.8.6/src'
\033[033mChecking librdkafka integrity\033[0m
librdkafka.so.1                \033[032mOK\033[0m
librdkafka.a                   \033[032mOK\033[0m
Symbol visibility              \033[32mOK\033[0m
make[1]: Leaving directory '/usr/local/src/librdkafka-0.8.6/work/librdkafka-0.8.6/src'
make[1]: Entering directory '/usr/local/src/librdkafka-0.8.6/work/librdkafka-0.8.6/src-cpp'
\033[033mChecking librdkafka++ integrity\033[0m
librdkafka++.so.1              \033[032mOK\033[0m
librdkafka++.a                 \033[032mOK\033[0m
make[1]: Leaving directory '/usr/local/src/librdkafka-0.8.6/work/librdkafka-0.8.6/src-cpp'
```
Environment:
```
TERM="screen"
SHELL="/bin/bash"
glibc-2.20
binutils-2.25
coreutils-8.23
```

**Comment by edenhill** [comment]
I have the same versions.
What is your bash and screen versions?
Does it work when not inside a screen?

**Comment by Whissi** [comment]
The main OS is Gentoo GNU Linux.

I tried via SSH in screen-4.2.1 or tmux-1.9a and also without any terminal multiplexers at all.
It also doesn't work when I am sitting directly in front of the system (tty).

Things like https://github.com/altercation/es-localbin/blob/master/colortest-linux are working fine on each terminal/terminal multiplexers like colored output in *dmesg* or other build systems like *CMake*.

**Comment by edenhill** [comment]
Weird, from what I understand mklove is using the standard escape codes:
https://github.com/edenhill/mklove/blob/master/modules/configure.base#L29

according to this:
http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/x329.html


Maybe the shell isn't bash (but busybox or similar, is $BASH_VERSION set?), or escape codes are disabled somehow?

**Comment by Whissi** [comment]
As said, it is bash:
```bash
$ echo $BASH_VERSION
4.3.33(1)-release
```

While reading `src/Makefile` from *librdkafka-0.8.6* I noticed it contains
```bash
check: file-check
        @(printf "%-30s " "Symbol visibility" ; \
        (($(SYMDUMPER) $(LIBFILENAME) | grep -q rd_kafka_new) && \
          ($(SYMDUMPER) $(LIBFILENAME) | grep -vq rd_kafka_destroy) && \
                echo "\033[32mOK\033[0m") || \
          echo "\033[31mFAILED\033[0m")
```
When I execute
```bash
$ echo "\033[32mOK\033[0m"
```
I don't get colored output. But when I execute
```bash
$ echo -e "\033[32mOK\033[0m"
```
I am getting colored output.

For testing I converted every `echo` call to `echo -e` and now it is working.


Do you remember why you did 5c715ccba3?

**Comment by edenhill** [comment]
If I remember correctly it was because standard /bin/sh, which `make` invokes by default, does not have the -e option.

**Comment by Whissi** [comment]
OK, I was wondering why you asked for *bash* but doesn't enforce bash usage in *mklove*. So you want to be portable? Great. Have you considered using `printf` for colored output? Should work on any platform. So you don't have to deal with different internal `echo` implementations.

**Comment by edenhill** [comment]
I'm not sure printf is available on SunOS, et.al.

Maybe the best approach is to set   SHELL=/bin/bash in Makefile.base ?

**Comment by Whissi** [comment]
SunOS should support `printf`.

I wouldn't add a dependency on *bash* just for colored output (remember shellshock). 3 options:
 1. Use `printf`
 2. Use `/bin/echo` instead of whatever is built-in
 3. Use colored output only when *bash* is available.

**Comment by edenhill** [comment]
Try the latest master, it uses `/bin/echo -e` in Makefile.base

**Comment by Whissi** [comment]
Looks better, but incomplete:
```
\033[033mGenerating linker script librdkafka++.lds from rdkafkacpp.h\033[0m
[...]
\033[33mUpdating CONFIGURATION.md\033[0m
[...]
Symbol visibility              \033[32mOK\033[0m
```

I also compared with Debian and noticed that these `checking for <...> ... ok` messages in the beginning are colorized in Debian. Not on Gentoo (but I also don't see escaped chars like in the quoted messages above).

**Comment by edenhill** [comment]
The ./configure script requires bash (Makefile.base doesn't) so I dont think color codes is not an issue there.

**Comment by edenhill** [comment]
The librdkafka specific makefiles now use $(ECHO) from mklove/Makefile.base, which should fix the last places.

**Comment by Whissi** [comment]
OK, the problem is the way mklove is checking color support in terminal:
```bash
if tty > /dev/null 2>&1 ; then
```
That's not a reliable way to catch most color-supporting terminals.

The most portable way to check for color support seems to be something like
```bash
use_color=false
if hash tput >/dev/null 2>&1 && [[ $(tput colors) -ge 8 ]]; then
    use_color=true
fi
```
But `tput` is not available on Cygwin. Also, checking if $TERM is known by `dircolors --print-database` seems to be a good idea to catch *lying* (prevent errors in yet unknown) terminals. But `dircolors` isn't available on MacOS for example.
To run different checks per OS it would be nice to use `$MKL_DISTRO` but currently we are checking for colors in the *base* module and `$MKL_DISTRO` will be initialized in the *host* module which will be loaded **after** the *base* module.

What I would do:
*base* module would just initialize empty color variables (like currently, if the terminal doesn't support colors).
I would add a new module named *color-support* which would do all these OS-dependent checks and alter the color variables if color support was detected.


Do you have a better idea?

**Comment by Whissi** [comment]
OK, I don't need to use `$$MKL_DISTRO`. It is enough to check for each tool on usage. No need for an own *color* module. I have a working prototype, I'll create a PR when I finished all the other color fixes.

**Comment by edenhill** [comment]
Awesome!
